---

- name: install auditd package | package-08
  package:
    name: '{{ auditd_package }}'
    state: 'present'
  when: os_auditd_enabled

- name: configure auditd | package-08
  template:
    src: 'etc/audit/auditd.conf.j2'
    dest: '/etc/audit/auditd.conf'
    owner: 'root'
    group: 'root'
    mode: '0640'
  when: os_auditd_enabled
