---
- name: install SELinux python bindings if SELinux is enabled
  package: name={{os_packages_libselinux_python}} state=present
  when: ansible_selinux.status == 'enabled'

- name: create login.defs
  template: src='login.defs.j2' dest='/etc/login.defs' owner=root group=root mode=0444

