---

- name: install modprobe to disable filesystems (for apt variants) | os-10
  apt:
    name: '{{ modprobe_package }}'
    state: 'present'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install modprobe to disable filesystems (for Yum variants) | os-10
  yum:
    name: '{{ modprobe_package }}'
    state: 'present'
    lock_timeout: 180
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Amazon Linux' or ansible_distribution == 'Fedora'

- name: check if efi is installed
  stat:
    path: "/sys/firmware/efi"
  register: efi_installed

- name: remove vfat from fs-list if efi is used
  set_fact:
    os_unused_filesystems: "{{ os_unused_filesystems | difference('vfat') }}"
  when: efi_installed.stat.isdir is defined and efi_installed.stat.isdir

- name: disable unused filesystems | os-10
  template:
    src: 'etc/modprobe.d/modprobe.j2'
    dest: '/etc/modprobe.d/dev-sec.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
