---
- name: remove unused repositories
  file:
    name: '/etc/yum.repos.d/{{ item }}.repo'
    state: 'absent'
  loop:
    - 'CentOS-Debuginfo'
    - 'CentOS-Media'
    - 'CentOS-Vault'
  when: os_security_packages_clean | bool

  # for the 'default([])' see here:
  # https://github.com/dev-sec/ansible-os-hardening/issues/99 and
  # https://stackoverflow.com/questions/37067827/ansible-deprecation-warning-for-undefined-variable-despite-when-clause
  #
  # failed_when is needed because by default replace module will fail if the file doesn't exists.
  # status.rc is only defined if an error accrued and only error code (rc) 257 will be ignored.
  # All other errors will still be raised.
- name: activate gpg-check for config files
  replace:
    dest: '{{ item }}'
    regexp: '^\s*gpgcheck: 0'
    replace: 'gpgcheck: 1'
  register: status
  failed_when: status.rc is defined and status.rc != 257
  with_flattened:
    - '/etc/yum.conf'
    - '/etc/dnf/dnf.conf'
    - '/etc/yum/pluginconf.d/rhnplugin.conf'

- name: activate gpg-check for repositories
  replace:
    dest: '{{ item }}'
    regexp: '^\s*gpgcheck: 0'
    replace: 'gpgcheck: 1'
  with_fileglob:
    - '/etc/yum.repos.d/*.repo'

- name: remove deprecated or insecure packages | package-01 - package-09
  yum:
    name: '{{ os_security_packages_list }}'
    state: 'absent'
  when: os_security_packages_clean | bool
