---

os_nologin_shell_path: '/sbin/nologin'

os_shadow_perms:
  owner: root
  group: root
  mode: '0600'

os_passwd_perms:
  owner: root
  group: root
  mode: '0644'

os_env_umask: '027'

os_auth_uid_min: 1000
os_auth_uid_max: 60000
os_auth_gid_min: 1000
os_auth_gid_max: 60000
os_auth_sys_uid_min: 500
os_auth_sys_uid_max: 999
os_auth_sys_gid_min: 500
os_auth_sys_gid_max: 999
os_auth_sub_uid_min: 100000
os_auth_sub_uid_max: 600100000
os_auth_sub_uid_count: 65536
os_auth_sub_gid_min: 100000
os_auth_sub_gid_max: 600100000
os_auth_sub_gid_count: 65536

modprobe_package: 'kmod'
auditd_package: 'audit'
os_auditd_rules_events_os:
  # System events must be logged. Telekom SoC 3.65 ReqID 32213164
  #   (Un)Installation of software
  - "-w /usr/bin/pacman -p x -k software_mgmt"
  # Access and Authentication events must be logged. Telekom SoC 3.65 ReqID f081ec34
  #   Logon and Logoff
  - "-w /var/run/faillock/ -p wa -k logins"
  # Configuration Change events must be logged. Telekom SoC 3.65 ReqID 5a090110
  #   Change of SELinux configuration
  - "-w /etc/selinux/ -p wa -k MAC-policy"
  #   Change of AppArmor configuration
  - "-w /etc/apparmor/ -p wa -k MAC-policy"
  - "-w /etc/apparmor.d/ -p wa -k MAC-policy"

hidepid_option: '2'  # allowed values: 0, 1, 2
