---

- name: create coredump.conf.d-directory if it does not exist
  file: path='/etc/systemd/coredump.conf.d' owner=root group=root mode=0755 state=directory
  when: ansible_service_mgr == "systemd"

- name: create custom.conf for disabling coredumps
  template: src='etc/systemd/coredump.conf.d/coredumps.conf.j2' dest='/etc/systemd/coredump.conf.d/custom.conf' owner=root group=root mode=0644
  when: ansible_service_mgr == "systemd"

- name: Reload daemon
  systemd:
    daemon_reload: yes

