---
- name: Add pinerolo_profile.sh to profile.d
  template:
    src: 'etc/profile.d/profile.conf.j2'
    dest: '/etc/profile.d/pinerolo_profile.sh'
    owner: 'root'
    group: 'root'
    mode: '0750'
  when: not os_security_kernel_enable_core_dump | bool

- name: Remove pinerolo_profile.sh from profile.d
  file:
    path: /etc/profile.d/pinerolo_profile.sh
    state: absent
  when: os_security_kernel_enable_core_dump | bool

- name: Add env security to profile
  template:
    src: 'etc/profile.d/os-security.j2'
    dest: '/etc/profile.d/os-security.sh'
    owner: 'root'
    group: 'root'
    mode: '0750'
  when: os_profile_security_enabled | bool

- name: Remove env os security to profile.d
  file:
    path: /etc/profile.d/os-security.sh
    state: absent
  when: not os_profile_security_enabled | bool
