---
- name: Read local linux user database
  getent:
    database: passwd
    #creates a dict for each user containing UID/HOMEDIR etc...
  when: getent_passwd is undefined # skip this task if "getent" has run before

- name: extract system accounts from local user database
  loop: "{{ getent_passwd.keys()|list }}"
  when:
    - getent_passwd[item][1]|int > 0
    - getent_passwd[item][1]|int <= os_auth_sys_uid_max|int
    - item is not in os_always_ignore_users     # skip users from "os_always_ignore_users" list (taken from role "vars")
    - item is not in os_ignore_users            # skip users from "os_ignore_users"        list (taken from role "defaults")
  set_fact:
    system_users: "{{ system_users|default([]) + [item] }}"

- name: remove shell+password for linux system accounts
  user:
    name: '{{ item }}'
    shell: '{{ os_nologin_shell_path }}'
    password: '*'
    createhome: false
  loop: "{{ system_users }}"

- name: get all home directories in /home, but skip ignored users
  find:
    paths: /home/
    recurse: false
    file_type: directory
    excludes: "{{ os_ignore_home_folder_users | join(',') }}"
  register: home_directories
  when: os_chmod_home_folders | bool

- name: set ownership of /home directories to 0700
  file:
    mode: 0700
    path: "{{ item.path }}"
    state: directory
  loop: "{{ home_directories.files }}"
  when: os_chmod_home_folders | bool
