---
- name: wrapper playbook for kitchen testing "ansible-postgres-hardening" with custom settings
  become: true
  hosts: all
  collections:
    - devsec.hardening
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') | default(omit)  }}"
    https_proxy: "{{ lookup('env', 'https_proxy') | default(omit) }}"
    no_proxy: "{{ lookup('env', 'no_proxy') | default(omit) }}"
  tasks:
    - include_role:
        name: postgres_hardening
