---
- name: prepare playbook for kitchen testing "ansible-postgres-hardening" with custom settings
  become: true
  hosts: all
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') | default(omit)  }}"
    https_proxy: "{{ lookup('env', 'https_proxy') | default(omit) }}"
    no_proxy: "{{ lookup('env', 'no_proxy') | default(omit) }}"
  tasks:
    - name: install required packages
      package:
        name: "python3-apt"
        update_cache: true
      ignore_errors: true # noqa ignore-errors

    - include_role:
        name: geerlingguy.postgresql
