---
name: Codespell - Spellcheck

on:  # yamllint disable-line rule:truthy
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ansible-lint:
    uses: dev-sec/.github/.github/workflows/codespell.yml@codespell
