---
name: "devsec.nginx_hardening"
on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - 'roles/nginx_hardening/**'
      - 'molecule/nginx_hardening/**'
      - '.github/workflows/nginx_hardening.yml'
  pull_request:
    paths:
      - 'roles/nginx_hardening/**'
      - 'molecule/nginx_hardening/**'
      - '.github/workflows/nginx_hardening.yml'
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        molecule_distro:
          - distro: centos7
          - distro: centos8
          - distro: fedora
          - distro: ubuntu1604
          - distro: ubuntu1804
          - distro: ubuntu2004
          - distro: debian9
          - distro: debian10
          - distro: amazon
          - distro: arch
          - distro: opensuse_tumbleweed
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: ansible_collections/devsec/hardening
          submodules: true

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          sudo apt install git
          python -m pip install --no-cache-dir --upgrade pip
          pip install -r requirements.txt
        working-directory: ansible_collections/devsec/hardening

      - name: Create default collection path symlink
        run: |
          mkdir -p /home/runner/.ansible
          ln -s /home/runner/work/ansible-os-hardening/ansible-os-hardening /home/runner/.ansible/collections

      - name: Test with molecule
        run: |
          molecule --version
          molecule test -s nginx_hardening
        env:
          MOLECULE_DISTRO: ${{ matrix.molecule_distro.distro }}
        working-directory: ansible_collections/devsec/hardening
